import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.scss";
import {Providers} from "@/components/providers/Providers";
import Navbar from "@/components/ui/navbar";
import UserModal from "@/components/ui/userModal";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Providers>
            <UserModal />
            <Navbar/>
            <body className={inter.className}>{children}</body>
        </Providers>
        </html>
    );
}
